drop table if exists t_task;
drop table if exists t_user;

create table t_task (
  id int generated by default as identity,
	title varchar(128) not null,
	description varchar(255),
	user_id bigint not null,
    primary key (id)
);

create table t_user (
  id int generated by default as identity,
	login_name varchar(64) not null unique,
	name varchar(64) not null,
	password varchar(255) not null,
	salt varchar(64) not null,
	roles varchar(255) not null,

	phone_No varchar(20) DEFAULT NULL,
	email varchar(20) DEFAULT NULL,
	dept_Id int(11) NOT NULL,

	primary key (id)
);

-- ----------------------------
-- Table structure for `t_dept`
-- ----------------------------
DROP TABLE IF EXISTS t_dept;
CREATE TABLE t_dept (
  id int generated by default as identity,
	sname varchar(255) not null unique,
  PRIMARY KEY (`id`)
);
-- ----------------------------
-- Records of t_dept
-- ----------------------------
--INSERT INTO `t_dept` VALUES ('100','培训中心');
--INSERT INTO `t_dept` VALUES ('101','研1');
--INSERT INTO `t_dept` VALUES ('102','研2');
--INSERT INTO `t_dept` VALUES ('103','研3');
--INSERT INTO `t_dept` VALUES ('104','质管');

-- ----------------------------
-- Table structure for `t_project`
-- ----------------------------
DROP TABLE IF EXISTS `t_project`;
CREATE TABLE `t_project` (
  id int generated by default as identity,
  `name` varchar(40) NOT NULL,
  `description` varchar(256) NOT NULL,
  `start_date` timestamp NOT NULL,
  `end_date` timestamp NOT NULL,
  `mandays` int NOT NULL,
  `status` int NOT NULL,
  PRIMARY KEY (`id`)
) ;

-- ----------------------------
-- Table structure for `t_plan`
-- ----------------------------
DROP TABLE IF EXISTS `t_plan`;
CREATE TABLE `t_plan` (
  id int generated by default as identity,
  `name` varchar(40) NOT NULL,
  `project_Id` int NOT NULL,
  `status` int(1) NOT NULL,
  PRIMARY KEY (`id`)
) ;

-- ----------------------------
-- Table structure for `t_course`
-- ----------------------------
DROP TABLE IF EXISTS `t_course`;
CREATE TABLE `t_course` (
  id int generated by default as identity,
  `name` varchar(40) NOT NULL,
  `start_date` date NOT NULL,
  `end_date` date NOT NULL,
  `numbers` int(11) NOT NULL,
  `plan_Id` int(11) NOT NULL,
  `status` int(1) DEFAULT 0,
  PRIMARY KEY (`id`)
) ;

-- ----------------------------
-- Table structure for `t_signup`
-- ----------------------------
DROP TABLE IF EXISTS `t_signup`;
CREATE TABLE `t_signup` (
  id int generated by default as identity,
  `course_Id` int(11) NOT NULL,
  `signer_Id` int(11) NOT NULL,
  `checkin_Id` int(11) DEFAULT NULL,
  `signup_Day` datetime DEFAULT null,
  PRIMARY KEY (`id`)
) ;

-- ----------------------------
-- Table structure for `t_checkin`
-- ----------------------------
DROP TABLE IF EXISTS `t_checkin`;
CREATE TABLE `t_checkin` (
  id int generated by default as identity,
  `course_Id` int(11) NOT NULL,
  `checkin_user_Id` int(11) NOT NULL,
  `checkin_Day` date NOT NULL,
  PRIMARY KEY (`id`)
) ;

-- ----------------------------
-- Table structure for `t_rungin`
-- ----------------------------
DROP TABLE IF EXISTS `t_rungin`;
CREATE TABLE `t_rungin` (
  id int generated by default as identity,
  `course_Id` int(11) NOT NULL,
  `rungin_user_Id` int(11) NOT NULL,
  `rungin_Day` date NOT NULL,
  `forenoon` int(1) DEFAULT 0,
  `plan_Id` int(11) NOT NULL,
  `project_Id` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ;
